import { NextResponse } from 'next/server';
import { acknowledgeByToken, lookupAckToken } from '@/lib/crisisRuntime';

// Tokenised acknowledgement endpoint — Appendix A method 2, the default per build
// plan v1.1 (no telco dependency, precise timestamp, supports ETA capture).
//
// PUBLIC BY DESIGN. A responder taps this link on their phone in the middle of a
// crisis; requiring a login would defeat the purpose. Security rests on the token
// being opaque and unguessable (see ackToken() in crisisRuntime.ts) and on the
// token being scoped to a single recipient in a single crisis.
//
// GET  ?token=…  → who this token belongs to, so the page can show the responder
//                  the actual crisis instead of a bare Yes/No prompt
// POST { token, decision, eta }
export async function GET(request: Request) {
  try {
    const token = new URL(request.url).searchParams.get('token');
    if (!token) return NextResponse.json({ error: 'Missing token.' }, { status: 400 });
    // Read-only. Deliberately NOT acknowledgeByToken() — merely opening the link
    // must never record an acknowledgement, or a link preview generated by the
    // recipient's messaging app would mark them as responding before they read it.
    const info = await lookupAckToken(token);
    if (!info) return NextResponse.json({ error: 'This acknowledgement link is not valid.' }, { status: 404 });
    return NextResponse.json(info);
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const { token, decision, eta } = await request.json();
    if (!token || (decision !== 'ACKNOWLEDGED' && decision !== 'DECLINED')) {
      return NextResponse.json({ error: 'Token and a valid decision are required.' }, { status: 400 });
    }
    const result = await acknowledgeByToken(token, decision, eta);
    if (!result.ok) return NextResponse.json({ error: 'This acknowledgement link is not valid.' }, { status: 404 });
    return NextResponse.json(result);
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
